apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-h3ke
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hvhp-tenant/rhtap-demo-app/hacbs-test-project-h3ke@sha256:b0e47558a3ab271fb0b48d3cdd5a3f5c93623003dd4886f3451684ad6d580dc6
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
