apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-h3ke
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-h3ke
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-h3ke
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-h3ke
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-h3ke
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hvhp-tenant/rhtap-demo-app/hacbs-test-project-h3ke@sha256:4e575ed888453f10c404a8d919c39c0c2ca0c4542c08b3c8497ab03c18cde352
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
